(defproject heratepalvelu "0.1.0-SNAPSHOT"
  :description "Herätepalvelu Arvo-kyselylinkkien lähetyksen automatisointiin."
  :repositories [["releases" "https://artifactory.opintopolku.fi/artifactory/oph-sade-release-local"]
                 ["snapshots" "https://artifactory.opintopolku.fi/artifactory/oph-sade-snapshot-local"]]
  :dependencies [[org.clojure/clojure]
                 [org.clojure/tools.logging]
                 [org.clojure/core.memoize]
                 [environ]
                 [clj-http]
                 [cheshire]
                 [clj-time]
                 [clj-tuple]
                 [com.amazonaws/aws-xray-recorder-sdk-core]
                 [com.amazonaws/aws-xray-recorder-sdk-aws-sdk-v2]
                 [com.amazonaws/aws-lambda-java-core]
                 [com.amazonaws/aws-lambda-java-events]
                 [dev.weavejester/medley]
                 [software.amazon.awssdk/dynamodb]
                 [software.amazon.awssdk/ssm]
                 [software.amazon.awssdk/sqs]
                 [org.apache.logging.log4j/log4j-api]
                 [org.apache.logging.log4j/log4j-core]
                 [org.apache.logging.log4j/log4j-slf4j-impl]
                 [prismatic/schema]
                 [hiccup]
                 [oph/clj-cas]
                 [com.googlecode.libphonenumber/libphonenumber]
                 [org.clojure/data.json]]
  :managed-dependencies [[org.clojure/clojure "1.12.0"]
                         [org.clojure/tools.logging "1.3.0"]
                         [org.clojure/core.memoize "1.1.266"]
                         [environ "1.2.0"]
                         [clj-http "3.13.0"]
                         [cheshire "5.13.0"]
                         [clj-time "0.15.2"]
                         [clj-tuple "0.2.2"]
                         [com.amazonaws/aws-xray-recorder-sdk-core "2.18.2"]
                         [com.amazonaws/aws-xray-recorder-sdk-aws-sdk-v2 "2.18.2"]
                         [com.amazonaws/aws-lambda-java-core "1.2.3"]
                         [com.amazonaws/aws-lambda-java-events "2.2.9"]
                         [dev.weavejester/medley "1.8.1"]
                         [software.amazon.awssdk/dynamodb "2.15.82"]
                         [software.amazon.awssdk/ssm "2.15.82"]
                         [software.amazon.awssdk/sqs "2.15.82"]
                         [org.apache.logging.log4j/log4j-api "2.24.1"]
                         [org.apache.logging.log4j/log4j-core "2.24.1"]
                         [org.apache.logging.log4j/log4j-slf4j-impl "2.24.1"]
                         [prismatic/schema "1.1.11"] ;
                         [hiccup "1.0.5"]
                         [oph/clj-cas "0.6.2-SNAPSHOT"]
                         [com.googlecode.libphonenumber/libphonenumber "8.13.49"]
                         [org.clojure/data.json "2.5.0"]

                         [software.amazon.awssdk/aws-core "2.15.82"]
                         [io.netty/netty-buffer "4.1.43.Final"] ;
                         [fi.vm.sade/scala-cas_2.12 "2.2.2.1-SNAPSHOT"]
                         [org.slf4j/slf4j-api "1.7.36"]
                         [com.fasterxml.jackson.core/jackson-core "2.18.1"]
                         [com.fasterxml.jackson.core/jackson-annotations "2.18.1"]
                         [com.fasterxml.jackson.core/jackson-databind "2.18.1"]
                         [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.18.1"]
                         [com.typesafe.akka/akka-actor_2.12 "2.5.16"]
                         [commons-io/commons-io "2.17.0"]]
  :plugins [[jonase/eastwood "1.2.3"]
            [lein-bikeshed "0.5.2"]
            [lein-cljfmt "0.8.0"]
            [lein-kibit "0.1.8"]]
  :aliases {"checkall" ["do"
                        ["kibit"]
                        ["bikeshed"]
                        ["eastwood"]
                        ["cljfmt" "check"]]}
  :cljfmt {:indents {cond->       [[:inner 0]]
                     definterface [[:inner 0]]
                     defschema    [[:inner 0]]
                     deftest      [[:inner 0]]
                     testing      [[:inner 0]]
                     with-redefs  [[:inner 0]]
                     #".*"        [[:block 0]]}}
  :eastwood {:add-linters [:no-ns-form-found
                           :unused-locals
                           :unused-namespaces
                           :unused-private-vars]}
  :aot :all
  :source-paths ["src"]
  :java-source-paths ["src/java"]
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}
             :test {:resource-paths ["test/resources"]}})
