service: heratepalvelu

custom:
  region: eu-west-1
  stage: ${opt:stage, 'sieni'}
  stack: ${self:custom.stage}-${self:service}
  herateTable: ${self:custom.stack}-herateTable
  eHOKSherateQueue: ${self:custom.stack}-eHOKSHerateQueue
  virkailija_url: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/virkailija-url~true}

provider:
  name: aws
  stackName: ${self:custom.stack}
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: java8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.herateTable}"
        - "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.herateTable}/index/lahetysIndex"
  environment:
    herate_table: ${self:custom.herateTable}
    region: ${self:custom.region}
    cas_url: ${self:custom.virkailija_url}/cas
    cas_user: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/cas-user~true}
    cas_pwd: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/cas-pwd~true}

package:
  artifact: target/uberjar/${self:service}-0.1.0-SNAPSHOT-standalone.jar
  exclude:
    - "*.txt"
    - "*.md"
    - "*.yml"
    - "*.json"
    - "*.xml"
    - "test/*"

functions:
  eHOKSherateHandler:
    name: ${self:custom.stack}-eHOKSherateHandler
    memorySize: 1024
    timeout: 30
    handler: oph.heratepalvelu.eHOKSherateHandler::handleHOKShyvaksytty
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - eHOKSHerateQueue
              - Arn
    environment:
      organisaatio_url: ${self:custom.virkailija_url}/organisaatio-service/rest/organisaatio/v4/
      koski_url: https://dev.koski.opintopolku.fi/koski/api/
      koski_user: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/koski-user~true}
      koski_pwd: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/koski-pwd~true}
      caller_id: ${self:custom.stack}-herateEmailHandler
  herateEmailHandler:
    name: ${self:custom.stack}-herateEmailHandler
    memorySize: 1024
    timeout: 30
    handler: oph.heratepalvelu.herateEmailHandler::handleSendEmails
    environment:
      caller_id: ${self:custom.stack}-herateEmailHandler
      viestintapalvelu_url: ${self:custom.virkailija_url}/ryhmasahkoposti-service/email
#    events:
#      - schedule: cron(0/15 10-16 * * ? *)



resources:
  Description: Herätepalvelu Arvo-kyselylinkkien lähettämiseen
  Resources:
    HerateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.herateTable}
        AttributeDefinitions:
          - AttributeName: toimija_oppija
            AttributeType: S
          - AttributeName: tyyppi_kausi
            AttributeType: S
          - AttributeName: lahetystila
            AttributeType: S
          - AttributeName: alkupvm
            AttributeType: S
        KeySchema:
          - AttributeName: toimija_oppija
            KeyType: HASH
          - AttributeName: tyyppi_kausi
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 20
          WriteCapacityUnits: 10
        SSESpecification:
          SSEEnabled: true
        GlobalSecondaryIndexes:
          - IndexName: lahetysIndex
            KeySchema:
              - AttributeName: lahetystila
                KeyType: HASH
              - AttributeName: alkupvm
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - sahkoposti
                - kyselylinkki
                - suorituskieli
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: '5'
              WriteCapacityUnits: '5'
    eHOKSHerateQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.eHOKSherateQueue}
