service: heratepalvelu

custom:
  region: eu-west-1
  stage: ${opt:stage, 'sieni'}
  stack: ${self:custom.stage}-${self:service}
  herateTable: ${self:custom.stack}-herateTable
  chekedLastTable: ${self:custom.stack}-checkedLastTable
  orgWhitelistTable: ${self:custom.stack}-organisaatioWhitelist
  eHOKSherateQueue: ${self:custom.stack}-eHOKSHerateQueue
  eHOKSherateDLQ: ${self:custom.stack}-eHOKSherateDLQ
  virkailija_url: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/virkailija-url~true}

provider:
  name: aws
  stackName: ${self:custom.stack}
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: java8
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.herateTable}"
        - "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.herateTable}/index/lahetysIndex"
        - "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.checkedLastTable}"
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt:
            - eHOKSherateDLQ
            - Arn
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.orgWhitelistTable}"
  environment:
    herate_table: ${self:custom.herateTable}
    orgwhitelist_table: ${self:custom.orgWhitelistTable}
    checkedlast_table: ${self:custom.checkedLastTable}
    region: ${self:custom.region}
    cas_url: ${self:custom.virkailija_url}/cas
    cas_user: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/cas-user~true}
    cas_pwd: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/cas-pwd~true}

package:
  artifact: target/uberjar/${self:service}-0.1.0-SNAPSHOT-standalone.jar
  exclude:
    - "*.txt"
    - "*.md"
    - "*.yml"
    - "*.json"
    - "*.xml"
    - "test/*"

functions:
  eHOKSherateHandler:
    name: ${self:custom.stack}-eHOKSherateHandler
    memorySize: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/ehokshandler-memory~true}
    timeout: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/ehokshandler-timeout~true}
    handler: oph.heratepalvelu.eHOKSherateHandler::handleHOKSherate
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - eHOKSHerateQueue
              - Arn
    environment:
      organisaatio_url: ${self:custom.virkailija_url}/organisaatio-service/rest/organisaatio/v4/
      koski_url: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/koski-url~true}
      koski_user: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/koski-user~true}
      koski_pwd: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/koski-pwd~true}
      caller_id: ${self:custom.stack}-herateEmailHandler
      arvo_url: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/arvo-url~true}
      arvo_user: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/arvo-user~true}
      arvo_pwd: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/arvo-pwd~true}
      ehoks_url: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/ehoks-url~true}
  herateEmailHandler:
    name: ${self:custom.stack}-herateEmailHandler
    memorySize: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/emailhandler-memory~true}
    timeout: ${ssm:/${self:custom.stage}/serverless/heratepalvelu/emailhandler-timeout~true}
    handler: oph.heratepalvelu.herateEmailHandler::handleSendEmails
    environment:
      caller_id: ${self:custom.stack}-herateEmailHandler
      viestintapalvelu_url: ${self:custom.virkailija_url}/ryhmasahkoposti-service/email
    events:
      - schedule: cron(${ssm:/${self:custom.stage}/serverless/heratepalvelu/emailhandler-cron~true})

resources:
  Description: Herätepalvelu Arvo-kyselylinkkien lähettämiseen
  Resources:
    EHOKSherateHandlerLogGroup:
      DependsOn: IamRoleLambdaExecution
    HerateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.herateTable}
        AttributeDefinitions:
          - AttributeName: toimija_oppija
            AttributeType: S
          - AttributeName: tyyppi_kausi
            AttributeType: S
          - AttributeName: lahetystila
            AttributeType: S
          - AttributeName: alkupvm
            AttributeType: S
        KeySchema:
          - AttributeName: toimija_oppija
            KeyType: HASH
          - AttributeName: tyyppi_kausi
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 20
          WriteCapacityUnits: 10
        SSESpecification:
          SSEEnabled: true
        GlobalSecondaryIndexes:
          - IndexName: lahetysIndex
            KeySchema:
              - AttributeName: lahetystila
                KeyType: HASH
              - AttributeName: alkupvm
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - sahkoposti
                - kyselylinkki
                - suorituskieli
                - viestintapalvelu-id
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: '5'
              WriteCapacityUnits: '5'
    organisaatioWhitelist:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.orgWhitelistTable}
        AttributeDefinitions:
          - AttributeName: organisaatio-oid
            AttributeType: S
        KeySchema:
          - AttributeName: organisaatio-oid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 20
          WriteCapacityUnits: 10
        SSESpecification:
          SSEEnabled: true
    checkedLastTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.checkedLastTable}
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        SSESpecification:
          SSEEnabled: true
    eHOKSHerateQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.eHOKSherateQueue}
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - eHOKSherateDLQ
              - Arn
          maxReceiveCount: 5
    eHOKSherateDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.eHOKSherateDLQ}
