name: heratepalvelu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: lein test
      - name: Static checks
        run: lein checkall
